### ISSUE TITLE
Only copy specific databases to memory

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-copy-to-memory#2]
I'd like to run this as a demo on https://latest-with-plugins.datasette.io/ but I don't want to copy all of the databases, just specific ones.

Can add some plugin configuration to support this.

**Comment by simonw** [comment]
```yaml
plugins:
  datasette-copy-to-memory:
    databases:
    - fixtures
```
If the configuration is missing it copies all databases.
